### ISSUE TITLE
Having parameter files instead of hard written parameters in MainTrunk

### ISSUE THREAD

**Issue by vanessa-king** [vanessa-king/UBC_LAIR#83] opened 2024-01-25 22:34 UTC
Debate! 
Instead of hard written parameters in MainTrunk.m, what if we had parameter files stored in the same path as your data that MainTrunk will read. 

Pros: Updating your local copy of UBC_LAIR wouldn't override the parameters you had already set for yourself

Cons: You would need really good documentation inside the parameter files in order to remember what each variable does, which could be confusing.

**Comment by m-altthaler** [comment] 2024-03-21 16:28
We could make a 'set variables block' at the top that set's stuff like folders e.g. and saves the assigned variable (i.e. the workspace). Then all you need to do is load that workspace (XYZ.mat file, which should be done in a 'load block') and all those variables will be assigned the correct values. 
The issue is this will not log properly unless we log all those variables when running the load block. 

You'd also have to suppress the reassignment in every block. Since you don't necessarily know which block you might run and what parameters you'd like to set when running them I don't think it's clever to force all those parameters to be set at the start.

**Comment by m-altthaler** [comment] 2024-11-01 20:28
no longer necessary as we use GUI for e.g. selection of data.

**Closed by m-altthaler** 2024-11-01 20:28 UTC
Labels: Controversy!
